"""The `runtime` facade.

Go groups the compatibility surface into ``api_model.go``, ``api_machine.go``,
``api_execution.go``, ``api_engine.go``, and ``api_session.go``, all in package
`runtime`. This module is that package: it re-exports each of those files and
adds nothing of its own, so ``runtime.Transition`` and ``runtime.MachineSnapshot``
read exactly as they do in Go.

Internal packages depend on the narrow package that owns a type, never on this
facade. R4 in ``tests/architecture/test_dependencies.py`` keeps the facade from
importing any concrete adapter, which is what stops it becoming a hub.
"""

from __future__ import annotations

from super_agent.runtime.api_engine import (
    COMPACT_SUMMARY_PROMPT as COMPACT_SUMMARY_PROMPT,
    Engine as Engine,
    EngineView as EngineView,
    NewEngine as NewEngine,
    NewEngineWithComponents as NewEngineWithComponents,
    NewEngineWithExecutor as NewEngineWithExecutor,
    NewEngineWithExecutorAndPolicy as NewEngineWithExecutorAndPolicy,
    PolicySetter as PolicySetter,
    PolicySnapshot as PolicySnapshot,
    PolicyStore as PolicyStore,
    StateObserver as StateObserver,
    cloneToolBatch as cloneToolBatch,
    errorString as errorString,
    estimateMessageTokens as estimateMessageTokens,
    estimateTokens as estimateTokens,
    millis_since as millis_since,
    typeName as typeName,
)
from super_agent.runtime.api_execution import (
    ActionCompletion as ActionCompletion,
    ActionID as ActionID,
    ActionQueue as ActionQueue,
    ActionResultInput as ActionResultInput,
    ActionResultResolver as ActionResultResolver,
    ApprovalDismissed as ApprovalDismissed,
    ApprovalKey as ApprovalKey,
    ApprovalReceived as ApprovalReceived,
    ApprovalStore as ApprovalStore,
    ApprovalWaiter as ApprovalWaiter,
    DefaultActionResultResolver as DefaultActionResultResolver,
    DefaultPolicy as DefaultPolicy,
    DefaultRunController as DefaultRunController,
    DefaultScheduledActionExecutor as DefaultScheduledActionExecutor,
    DefaultScheduledActionRunner as DefaultScheduledActionRunner,
    ErrApprovalDismissed as ErrApprovalDismissed,
    MemoryApprovalStore as MemoryApprovalStore,
    ModelReplied as ModelReplied,
    NewApprovalKey as NewApprovalKey,
    NewDefaultPolicy as NewDefaultPolicy,
    NewPolicy as NewPolicy,
    PermissionMode as PermissionMode,
    PermissionModeAcceptEdits as PermissionModeAcceptEdits,
    PermissionModeAsk as PermissionModeAsk,
    PermissionModeBypass as PermissionModeBypass,
    PermissionModePlan as PermissionModePlan,
    PermissionRules as PermissionRules,
    Policy as Policy,
    QueuedAction as QueuedAction,
    RunController as RunController,
    RunID as RunID,
    ScheduledActionExecutor as ScheduledActionExecutor,
    ScheduledActionInput as ScheduledActionInput,
    ScheduledActionResult as ScheduledActionResult,
    ScheduledActionRunner as ScheduledActionRunner,
    ToolDecision as ToolDecision,
    ToolFinished as ToolFinished,
    ToolPolicyInput as ToolPolicyInput,
    ToolQueueChecked as ToolQueueChecked,
    ValidPermissionMode as ValidPermissionMode,
    hashCanonicalInput as hashCanonicalInput,
)
from super_agent.runtime.api_machine import (
    ActionPlan as ActionPlan,
    AdvanceToolCallBatch as AdvanceToolCallBatch,
    AllEvents as AllEvents,
    AllRuntimeDataChanges as AllRuntimeDataChanges,
    AllScheduledActions as AllScheduledActions,
    AppendAssistantMessage as AppendAssistantMessage,
    AppendStreamingAssistant as AppendStreamingAssistant,
    AppendToolResult as AppendToolResult,
    AppendUserMessage as AppendUserMessage,
    ApprovalAlwaysGranted as ApprovalAlwaysGranted,
    ApprovalDecision as ApprovalDecision,
    ApprovalDenied as ApprovalDenied,
    ApprovalGranted as ApprovalGranted,
    ApproveAlways as ApproveAlways,
    ApproveOnce as ApproveOnce,
    AssistantMessageReceived as AssistantMessageReceived,
    AwaitApproval as AwaitApproval,
    CallModel as CallModel,
    CancelRequested as CancelRequested,
    CheckToolQueue as CheckToolQueue,
    ClearCurrentTool as ClearCurrentTool,
    ClearPendingTool as ClearPendingTool,
    ClearToolCallBatch as ClearToolCallBatch,
    DefaultRuntimeDataChangeApplier as DefaultRuntimeDataChangeApplier,
    DenyApproval as DenyApproval,
    EngineReady as EngineReady,
    ErrorOccurred as ErrorOccurred,
    Event as Event,
    FlushStreamingAssistant as FlushStreamingAssistant,
    InvariantViolationError as InvariantViolationError,
    MachineSnapshot as MachineSnapshot,
    ProtocolViolationError as ProtocolViolationError,
    ResetConversation as ResetConversation,
    ResetRequested as ResetRequested,
    RuntimeData as RuntimeData,
    RuntimeDataChange as RuntimeDataChange,
    RuntimeDataChangeApplier as RuntimeDataChangeApplier,
    RuntimeDataChangeResult as RuntimeDataChangeResult,
    RunTool as RunTool,
    ScheduledAction as ScheduledAction,
    SetCurrentTool as SetCurrentTool,
    SetPendingTool as SetPendingTool,
    SetToolCallBatch as SetToolCallBatch,
    SnapshotFrom as SnapshotFrom,
    ToolBatchFinished as ToolBatchFinished,
    ToolBatchReceived as ToolBatchReceived,
    ToolCallDenied as ToolCallDenied,
    ToolCallNeedsApproval as ToolCallNeedsApproval,
    ToolCallReadyToRun as ToolCallReadyToRun,
    ToolResultReceived as ToolResultReceived,
    Transition as Transition,
    TransitionResult as TransitionResult,
    UnexpectedEventError as UnexpectedEventError,
    UserMessageSubmitted as UserMessageSubmitted,
    ValidateRuntimeData as ValidateRuntimeData,
    ZeroState as ZeroState,
)
from super_agent.runtime.api_model import (
    Attachment as Attachment,
    CommandClass as CommandClass,
    Message as Message,
    Model as Model,
    ModelResponse as ModelResponse,
    PermissionRequest as PermissionRequest,
    Role as Role,
    RoleAssistant as RoleAssistant,
    RoleSystem as RoleSystem,
    RoleTool as RoleTool,
    RoleUser as RoleUser,
    State as State,
    StateAdvancingQueue as StateAdvancingQueue,
    StateIdle as StateIdle,
    StateInitializing as StateInitializing,
    StateRunningTool as StateRunningTool,
    StateWaitingApproval as StateWaitingApproval,
    StateWaitingLLM as StateWaitingLLM,
    StreamChunk as StreamChunk,
    ToolCall as ToolCall,
    ToolCallBatch as ToolCallBatch,
    ToolRunner as ToolRunner,
    ToolSpec as ToolSpec,
)
from super_agent.runtime.api_session import (
    AuditEvent as AuditEvent,
    CreatePersistentSession as CreatePersistentSession,
    FileSnapshot as FileSnapshot,
    MessageAppended as MessageAppended,
    Metadata as Metadata,
    NewPersistentSession as NewPersistentSession,
    NewSession as NewSession,
    Repository as Repository,
    Session as Session,
    SessionError as SessionError,
    SessionID as SessionID,
    SessionNotification as SessionNotification,
    StateChanged as StateChanged,
    StreamChunkReceived as StreamChunkReceived,
    Summary as Summary,
    ToolApprovalCleared as ToolApprovalCleared,
    ToolApprovalRequested as ToolApprovalRequested,
    Workspace as Workspace,
    WorkspaceAccessMode as WorkspaceAccessMode,
    WorkspaceAccessRead as WorkspaceAccessRead,
    WorkspaceAccessReadWrite as WorkspaceAccessReadWrite,
    WorkspaceRootSpec as WorkspaceRootSpec,
    WorkspaceSpec as WorkspaceSpec,
)

__all__ = [
    "COMPACT_SUMMARY_PROMPT",
    "ActionCompletion",
    "ActionID",
    "ActionPlan",
    "ActionQueue",
    "ActionResultInput",
    "ActionResultResolver",
    "AdvanceToolCallBatch",
    "AllEvents",
    "AllRuntimeDataChanges",
    "AllScheduledActions",
    "AppendAssistantMessage",
    "AppendStreamingAssistant",
    "AppendToolResult",
    "AppendUserMessage",
    "ApprovalAlwaysGranted",
    "ApprovalDecision",
    "ApprovalDenied",
    "ApprovalDismissed",
    "ApprovalGranted",
    "ApprovalKey",
    "ApprovalReceived",
    "ApprovalStore",
    "ApprovalWaiter",
    "ApproveAlways",
    "ApproveOnce",
    "AssistantMessageReceived",
    "Attachment",
    "AuditEvent",
    "AwaitApproval",
    "CallModel",
    "CancelRequested",
    "CheckToolQueue",
    "ClearCurrentTool",
    "ClearPendingTool",
    "ClearToolCallBatch",
    "CommandClass",
    "CreatePersistentSession",
    "DefaultActionResultResolver",
    "DefaultPolicy",
    "DefaultRunController",
    "DefaultRuntimeDataChangeApplier",
    "DefaultScheduledActionExecutor",
    "DefaultScheduledActionRunner",
    "DenyApproval",
    "Engine",
    "EngineReady",
    "EngineView",
    "ErrApprovalDismissed",
    "ErrorOccurred",
    "Event",
    "FileSnapshot",
    "FlushStreamingAssistant",
    "InvariantViolationError",
    "MachineSnapshot",
    "MemoryApprovalStore",
    "Message",
    "MessageAppended",
    "Metadata",
    "Model",
    "ModelReplied",
    "ModelResponse",
    "NewApprovalKey",
    "NewDefaultPolicy",
    "NewEngine",
    "NewEngineWithComponents",
    "NewEngineWithExecutor",
    "NewEngineWithExecutorAndPolicy",
    "NewPersistentSession",
    "NewPolicy",
    "NewSession",
    "PermissionMode",
    "PermissionModeAcceptEdits",
    "PermissionModeAsk",
    "PermissionModeBypass",
    "PermissionModePlan",
    "PermissionRequest",
    "PermissionRules",
    "Policy",
    "PolicySetter",
    "PolicySnapshot",
    "PolicyStore",
    "ProtocolViolationError",
    "QueuedAction",
    "Repository",
    "ResetConversation",
    "ResetRequested",
    "Role",
    "RoleAssistant",
    "RoleSystem",
    "RoleTool",
    "RoleUser",
    "RunController",
    "RunID",
    "RunTool",
    "RuntimeData",
    "RuntimeDataChange",
    "RuntimeDataChangeApplier",
    "RuntimeDataChangeResult",
    "ScheduledAction",
    "ScheduledActionExecutor",
    "ScheduledActionInput",
    "ScheduledActionResult",
    "ScheduledActionRunner",
    "Session",
    "SessionError",
    "SessionID",
    "SessionNotification",
    "SetCurrentTool",
    "SetPendingTool",
    "SetToolCallBatch",
    "SnapshotFrom",
    "State",
    "StateAdvancingQueue",
    "StateChanged",
    "StateIdle",
    "StateInitializing",
    "StateObserver",
    "StateRunningTool",
    "StateWaitingApproval",
    "StateWaitingLLM",
    "StreamChunk",
    "StreamChunkReceived",
    "Summary",
    "ToolApprovalCleared",
    "ToolApprovalRequested",
    "ToolBatchFinished",
    "ToolBatchReceived",
    "ToolCall",
    "ToolCallBatch",
    "ToolCallDenied",
    "ToolCallNeedsApproval",
    "ToolCallReadyToRun",
    "ToolDecision",
    "ToolFinished",
    "ToolPolicyInput",
    "ToolQueueChecked",
    "ToolResultReceived",
    "ToolRunner",
    "ToolSpec",
    "Transition",
    "TransitionResult",
    "UnexpectedEventError",
    "UserMessageSubmitted",
    "ValidPermissionMode",
    "ValidateRuntimeData",
    "Workspace",
    "WorkspaceAccessMode",
    "WorkspaceAccessRead",
    "WorkspaceAccessReadWrite",
    "WorkspaceRootSpec",
    "WorkspaceSpec",
    "ZeroState",
    "cloneToolBatch",
    "errorString",
    "estimateMessageTokens",
    "estimateTokens",
    "hashCanonicalInput",
    "millis_since",
    "typeName",
]
