"""The `runtime` facade.

The compatibility surface is grouped into ``api_model.py``, ``api_machine.py``,
``api_execution.py``, ``api_engine.py``, and ``api_session.py``, all in package
`runtime`. This module is that package: it re-exports each of those modules and
adds nothing of its own, so ``runtime.transition`` and ``runtime.MachineSnapshot``
are reachable from one place.

Internal packages depend on the narrow package that owns a type, never on this
facade. R4 in ``tests/architecture/test_dependencies.py`` keeps the facade from
importing any concrete adapter, which is what stops it becoming a hub.
"""

from __future__ import annotations

from super_agent.runtime.api_engine import (
    COMPACT_SUMMARY_PROMPT as COMPACT_SUMMARY_PROMPT,
    Engine as Engine,
    EngineView as EngineView,
    ModelUsageObserver as ModelUsageObserver,
    PolicySetter as PolicySetter,
    PolicySnapshot as PolicySnapshot,
    PolicyStore as PolicyStore,
    StateObserver as StateObserver,
    cloneToolBatch as cloneToolBatch,
    errorString as errorString,
    estimateMessageTokens as estimateMessageTokens,
    estimateTokens as estimateTokens,
    millis_since as millis_since,
    new_engine as new_engine,
    new_engine_with_components as new_engine_with_components,
    new_engine_with_executor as new_engine_with_executor,
    new_engine_with_executor_and_policy as new_engine_with_executor_and_policy,
    typeName as typeName,
)
from super_agent.runtime.api_execution import (
    ERR_APPROVAL_DISMISSED as ERR_APPROVAL_DISMISSED,
    PERMISSION_MODE_ACCEPT_EDITS as PERMISSION_MODE_ACCEPT_EDITS,
    PERMISSION_MODE_ASK as PERMISSION_MODE_ASK,
    PERMISSION_MODE_BYPASS as PERMISSION_MODE_BYPASS,
    PERMISSION_MODE_PLAN as PERMISSION_MODE_PLAN,
    ActionCompletion as ActionCompletion,
    ActionID as ActionID,
    ActionQueue as ActionQueue,
    ActionResultInput as ActionResultInput,
    ActionResultResolver as ActionResultResolver,
    ApprovalDismissed as ApprovalDismissed,
    ApprovalKey as ApprovalKey,
    ApprovalReceived as ApprovalReceived,
    ApprovalStore as ApprovalStore,
    ApprovalWaiter as ApprovalWaiter,
    DefaultActionResultResolver as DefaultActionResultResolver,
    DefaultPolicy as DefaultPolicy,
    DefaultRunController as DefaultRunController,
    DefaultScheduledActionExecutor as DefaultScheduledActionExecutor,
    DefaultScheduledActionRunner as DefaultScheduledActionRunner,
    MemoryApprovalStore as MemoryApprovalStore,
    ModelReplied as ModelReplied,
    PermissionMode as PermissionMode,
    PermissionRules as PermissionRules,
    Policy as Policy,
    QueuedAction as QueuedAction,
    RunController as RunController,
    RunID as RunID,
    ScheduledActionExecutor as ScheduledActionExecutor,
    ScheduledActionInput as ScheduledActionInput,
    ScheduledActionResult as ScheduledActionResult,
    ScheduledActionRunner as ScheduledActionRunner,
    ToolDecision as ToolDecision,
    ToolFinished as ToolFinished,
    ToolPolicyInput as ToolPolicyInput,
    ToolQueueChecked as ToolQueueChecked,
    hashCanonicalInput as hashCanonicalInput,
    new_approval_key as new_approval_key,
    new_default_policy as new_default_policy,
    new_policy as new_policy,
    valid_permission_mode as valid_permission_mode,
)
from super_agent.runtime.api_machine import (
    ALL_EVENTS as ALL_EVENTS,
    ALL_RUNTIME_DATA_CHANGES as ALL_RUNTIME_DATA_CHANGES,
    ALL_SCHEDULED_ACTIONS as ALL_SCHEDULED_ACTIONS,
    APPROVE_ALWAYS as APPROVE_ALWAYS,
    APPROVE_ONCE as APPROVE_ONCE,
    DENY_APPROVAL as DENY_APPROVAL,
    ZERO_STATE as ZERO_STATE,
    ActionPlan as ActionPlan,
    AdvanceToolCallBatch as AdvanceToolCallBatch,
    AppendAssistantMessage as AppendAssistantMessage,
    AppendStreamingAssistant as AppendStreamingAssistant,
    AppendToolResult as AppendToolResult,
    AppendUserMessage as AppendUserMessage,
    ApprovalAlwaysGranted as ApprovalAlwaysGranted,
    ApprovalDecision as ApprovalDecision,
    ApprovalDenied as ApprovalDenied,
    ApprovalGranted as ApprovalGranted,
    AssistantMessageReceived as AssistantMessageReceived,
    AwaitApproval as AwaitApproval,
    CallModel as CallModel,
    CancelRequested as CancelRequested,
    CheckToolQueue as CheckToolQueue,
    ClearCurrentTool as ClearCurrentTool,
    ClearPendingTool as ClearPendingTool,
    ClearToolCallBatch as ClearToolCallBatch,
    DefaultRuntimeDataChangeApplier as DefaultRuntimeDataChangeApplier,
    EngineReady as EngineReady,
    ErrorOccurred as ErrorOccurred,
    Event as Event,
    FlushStreamingAssistant as FlushStreamingAssistant,
    InvariantViolationError as InvariantViolationError,
    MachineSnapshot as MachineSnapshot,
    ProtocolViolationError as ProtocolViolationError,
    ResetConversation as ResetConversation,
    ResetRequested as ResetRequested,
    RuntimeData as RuntimeData,
    RuntimeDataChange as RuntimeDataChange,
    RuntimeDataChangeApplier as RuntimeDataChangeApplier,
    RuntimeDataChangeResult as RuntimeDataChangeResult,
    RunTool as RunTool,
    ScheduledAction as ScheduledAction,
    SetCurrentTool as SetCurrentTool,
    SetPendingTool as SetPendingTool,
    SetToolCallBatch as SetToolCallBatch,
    ToolBatchFinished as ToolBatchFinished,
    ToolBatchReceived as ToolBatchReceived,
    ToolCallDenied as ToolCallDenied,
    ToolCallNeedsApproval as ToolCallNeedsApproval,
    ToolCallReadyToRun as ToolCallReadyToRun,
    ToolResultReceived as ToolResultReceived,
    TransitionResult as TransitionResult,
    UnexpectedEventError as UnexpectedEventError,
    UserMessageSubmitted as UserMessageSubmitted,
    snapshot_from as snapshot_from,
    transition as transition,
    validate_runtime_data as validate_runtime_data,
)
from super_agent.runtime.api_model import (
    ROLE_ASSISTANT as ROLE_ASSISTANT,
    ROLE_SYSTEM as ROLE_SYSTEM,
    ROLE_TOOL as ROLE_TOOL,
    ROLE_USER as ROLE_USER,
    STATE_ADVANCING_QUEUE as STATE_ADVANCING_QUEUE,
    STATE_IDLE as STATE_IDLE,
    STATE_INITIALIZING as STATE_INITIALIZING,
    STATE_RUNNING_TOOL as STATE_RUNNING_TOOL,
    STATE_WAITING_APPROVAL as STATE_WAITING_APPROVAL,
    STATE_WAITING_LLM as STATE_WAITING_LLM,
    Attachment as Attachment,
    CommandClass as CommandClass,
    Message as Message,
    Model as Model,
    ModelResponse as ModelResponse,
    PermissionRequest as PermissionRequest,
    Role as Role,
    State as State,
    StreamChunk as StreamChunk,
    ToolCall as ToolCall,
    ToolCallBatch as ToolCallBatch,
    ToolRunner as ToolRunner,
    ToolSpec as ToolSpec,
    Usage as Usage,
)
from super_agent.runtime.api_session import (
    WORKSPACE_ACCESS_READ as WORKSPACE_ACCESS_READ,
    WORKSPACE_ACCESS_READ_WRITE as WORKSPACE_ACCESS_READ_WRITE,
    AuditEvent as AuditEvent,
    FileSnapshot as FileSnapshot,
    MessageAppended as MessageAppended,
    Metadata as Metadata,
    Repository as Repository,
    Session as Session,
    SessionError as SessionError,
    SessionID as SessionID,
    SessionNotification as SessionNotification,
    StateChanged as StateChanged,
    StreamChunkReceived as StreamChunkReceived,
    Summary as Summary,
    ToolApprovalCleared as ToolApprovalCleared,
    ToolApprovalRequested as ToolApprovalRequested,
    UsageReported as UsageReported,
    Workspace as Workspace,
    WorkspaceAccessMode as WorkspaceAccessMode,
    WorkspaceRootSpec as WorkspaceRootSpec,
    WorkspaceSpec as WorkspaceSpec,
    create_persistent_session as create_persistent_session,
    new_persistent_session as new_persistent_session,
    new_session as new_session,
)

__all__ = [
    "ALL_EVENTS",
    "ALL_RUNTIME_DATA_CHANGES",
    "ALL_SCHEDULED_ACTIONS",
    "APPROVE_ALWAYS",
    "APPROVE_ONCE",
    "COMPACT_SUMMARY_PROMPT",
    "DENY_APPROVAL",
    "ERR_APPROVAL_DISMISSED",
    "PERMISSION_MODE_ACCEPT_EDITS",
    "PERMISSION_MODE_ASK",
    "PERMISSION_MODE_BYPASS",
    "PERMISSION_MODE_PLAN",
    "ROLE_ASSISTANT",
    "ROLE_SYSTEM",
    "ROLE_TOOL",
    "ROLE_USER",
    "STATE_ADVANCING_QUEUE",
    "STATE_IDLE",
    "STATE_INITIALIZING",
    "STATE_RUNNING_TOOL",
    "STATE_WAITING_APPROVAL",
    "STATE_WAITING_LLM",
    "WORKSPACE_ACCESS_READ",
    "WORKSPACE_ACCESS_READ_WRITE",
    "ZERO_STATE",
    "ActionCompletion",
    "ActionID",
    "ActionPlan",
    "ActionQueue",
    "ActionResultInput",
    "ActionResultResolver",
    "AdvanceToolCallBatch",
    "AppendAssistantMessage",
    "AppendStreamingAssistant",
    "AppendToolResult",
    "AppendUserMessage",
    "ApprovalAlwaysGranted",
    "ApprovalDecision",
    "ApprovalDenied",
    "ApprovalDismissed",
    "ApprovalGranted",
    "ApprovalKey",
    "ApprovalReceived",
    "ApprovalStore",
    "ApprovalWaiter",
    "AssistantMessageReceived",
    "Attachment",
    "AuditEvent",
    "AwaitApproval",
    "CallModel",
    "CancelRequested",
    "CheckToolQueue",
    "ClearCurrentTool",
    "ClearPendingTool",
    "ClearToolCallBatch",
    "CommandClass",
    "DefaultActionResultResolver",
    "DefaultPolicy",
    "DefaultRunController",
    "DefaultRuntimeDataChangeApplier",
    "DefaultScheduledActionExecutor",
    "DefaultScheduledActionRunner",
    "Engine",
    "EngineReady",
    "EngineView",
    "ErrorOccurred",
    "Event",
    "FileSnapshot",
    "FlushStreamingAssistant",
    "InvariantViolationError",
    "MachineSnapshot",
    "MemoryApprovalStore",
    "Message",
    "MessageAppended",
    "Metadata",
    "Model",
    "ModelReplied",
    "ModelResponse",
    "ModelUsageObserver",
    "PermissionMode",
    "PermissionRequest",
    "PermissionRules",
    "Policy",
    "PolicySetter",
    "PolicySnapshot",
    "PolicyStore",
    "ProtocolViolationError",
    "QueuedAction",
    "Repository",
    "ResetConversation",
    "ResetRequested",
    "Role",
    "RunController",
    "RunID",
    "RunTool",
    "RuntimeData",
    "RuntimeDataChange",
    "RuntimeDataChangeApplier",
    "RuntimeDataChangeResult",
    "ScheduledAction",
    "ScheduledActionExecutor",
    "ScheduledActionInput",
    "ScheduledActionResult",
    "ScheduledActionRunner",
    "Session",
    "SessionError",
    "SessionID",
    "SessionNotification",
    "SetCurrentTool",
    "SetPendingTool",
    "SetToolCallBatch",
    "State",
    "StateChanged",
    "StateObserver",
    "StreamChunk",
    "StreamChunkReceived",
    "Summary",
    "ToolApprovalCleared",
    "ToolApprovalRequested",
    "ToolBatchFinished",
    "ToolBatchReceived",
    "ToolCall",
    "ToolCallBatch",
    "ToolCallDenied",
    "ToolCallNeedsApproval",
    "ToolCallReadyToRun",
    "ToolDecision",
    "ToolFinished",
    "ToolPolicyInput",
    "ToolQueueChecked",
    "ToolResultReceived",
    "ToolRunner",
    "ToolSpec",
    "TransitionResult",
    "UnexpectedEventError",
    "Usage",
    "UsageReported",
    "UserMessageSubmitted",
    "Workspace",
    "WorkspaceAccessMode",
    "WorkspaceRootSpec",
    "WorkspaceSpec",
    "cloneToolBatch",
    "create_persistent_session",
    "errorString",
    "estimateMessageTokens",
    "estimateTokens",
    "hashCanonicalInput",
    "millis_since",
    "new_approval_key",
    "new_default_policy",
    "new_engine",
    "new_engine_with_components",
    "new_engine_with_executor",
    "new_engine_with_executor_and_policy",
    "new_persistent_session",
    "new_policy",
    "new_session",
    "snapshot_from",
    "transition",
    "typeName",
    "valid_permission_mode",
    "validate_runtime_data",
]
