"""Facade re-exports for ``runtime/machine``.

This re-exports the machine's whole vocabulary so the rest of the program can
write ``runtime.transition``. It must NOT reintroduce the
retired ``ToolCallsReceived``, ``ToolCallAvailable``, ``EventClassifier``, or
``ResultResolver`` names: those were replaced by ``ToolBatchReceived`` and
``ActionResultResolver``, and their absence is what stops an adapter from drifting
back to the older shape.
"""

from __future__ import annotations

from super_agent.runtime.machine import (
    ALL_EVENTS as ALL_EVENTS,
    ALL_RUNTIME_DATA_CHANGES as ALL_RUNTIME_DATA_CHANGES,
    ALL_SCHEDULED_ACTIONS as ALL_SCHEDULED_ACTIONS,
    APPROVE_ALWAYS as APPROVE_ALWAYS,
    APPROVE_ONCE as APPROVE_ONCE,
    DENY_APPROVAL as DENY_APPROVAL,
    ZERO_STATE as ZERO_STATE,
    ActionPlan as ActionPlan,
    AdvanceToolCallBatch as AdvanceToolCallBatch,
    AppendAssistantMessage as AppendAssistantMessage,
    AppendStreamingAssistant as AppendStreamingAssistant,
    AppendToolResult as AppendToolResult,
    AppendUserMessage as AppendUserMessage,
    ApprovalAlwaysGranted as ApprovalAlwaysGranted,
    ApprovalDecision as ApprovalDecision,
    ApprovalDenied as ApprovalDenied,
    ApprovalGranted as ApprovalGranted,
    AssistantMessageReceived as AssistantMessageReceived,
    AwaitApproval as AwaitApproval,
    CallModel as CallModel,
    CancelRequested as CancelRequested,
    CheckToolQueue as CheckToolQueue,
    ClearCurrentTool as ClearCurrentTool,
    ClearPendingTool as ClearPendingTool,
    ClearToolCallBatch as ClearToolCallBatch,
    DefaultRuntimeDataChangeApplier as DefaultRuntimeDataChangeApplier,
    EngineReady as EngineReady,
    ErrorOccurred as ErrorOccurred,
    Event as Event,
    FlushStreamingAssistant as FlushStreamingAssistant,
    InvariantViolationError as InvariantViolationError,
    MachineSnapshot as MachineSnapshot,
    ProtocolViolationError as ProtocolViolationError,
    ResetConversation as ResetConversation,
    ResetRequested as ResetRequested,
    RuntimeData as RuntimeData,
    RuntimeDataChange as RuntimeDataChange,
    RuntimeDataChangeApplier as RuntimeDataChangeApplier,
    RuntimeDataChangeResult as RuntimeDataChangeResult,
    RunTool as RunTool,
    ScheduledAction as ScheduledAction,
    SetCurrentTool as SetCurrentTool,
    SetPendingTool as SetPendingTool,
    SetToolCallBatch as SetToolCallBatch,
    ToolBatchFinished as ToolBatchFinished,
    ToolBatchReceived as ToolBatchReceived,
    ToolCallDenied as ToolCallDenied,
    ToolCallNeedsApproval as ToolCallNeedsApproval,
    ToolCallReadyToRun as ToolCallReadyToRun,
    ToolResultReceived as ToolResultReceived,
    TransitionResult as TransitionResult,
    UnexpectedEventError as UnexpectedEventError,
    UserMessageSubmitted as UserMessageSubmitted,
    snapshot_from as snapshot_from,
    transition as transition,
    validate_runtime_data as validate_runtime_data,
)

__all__ = [
    "ALL_EVENTS",
    "ALL_RUNTIME_DATA_CHANGES",
    "ALL_SCHEDULED_ACTIONS",
    "APPROVE_ALWAYS",
    "APPROVE_ONCE",
    "DENY_APPROVAL",
    "ZERO_STATE",
    "ActionPlan",
    "AdvanceToolCallBatch",
    "AppendAssistantMessage",
    "AppendStreamingAssistant",
    "AppendToolResult",
    "AppendUserMessage",
    "ApprovalAlwaysGranted",
    "ApprovalDecision",
    "ApprovalDenied",
    "ApprovalGranted",
    "AssistantMessageReceived",
    "AwaitApproval",
    "CallModel",
    "CancelRequested",
    "CheckToolQueue",
    "ClearCurrentTool",
    "ClearPendingTool",
    "ClearToolCallBatch",
    "DefaultRuntimeDataChangeApplier",
    "EngineReady",
    "ErrorOccurred",
    "Event",
    "FlushStreamingAssistant",
    "InvariantViolationError",
    "MachineSnapshot",
    "ProtocolViolationError",
    "ResetConversation",
    "ResetRequested",
    "RunTool",
    "RuntimeData",
    "RuntimeDataChange",
    "RuntimeDataChangeApplier",
    "RuntimeDataChangeResult",
    "ScheduledAction",
    "SetCurrentTool",
    "SetPendingTool",
    "SetToolCallBatch",
    "ToolBatchFinished",
    "ToolBatchReceived",
    "ToolCallDenied",
    "ToolCallNeedsApproval",
    "ToolCallReadyToRun",
    "ToolResultReceived",
    "TransitionResult",
    "UnexpectedEventError",
    "UserMessageSubmitted",
    "snapshot_from",
    "transition",
    "validate_runtime_data",
]
