"""Facade re-exports for ``runtime/machine``.

This re-exports the machine's whole vocabulary so the rest of the program can
write ``runtime.Transition``. It must NOT reintroduce the
retired ``ToolCallsReceived``, ``ToolCallAvailable``, ``EventClassifier``, or
``ResultResolver`` names: those were replaced by ``ToolBatchReceived`` and
``ActionResultResolver``, and their absence is what stops an adapter from drifting
back to the older shape.
"""

from __future__ import annotations

from super_agent.runtime.machine import (
    ActionPlan as ActionPlan,
    AdvanceToolCallBatch as AdvanceToolCallBatch,
    AllEvents as AllEvents,
    AllRuntimeDataChanges as AllRuntimeDataChanges,
    AllScheduledActions as AllScheduledActions,
    AppendAssistantMessage as AppendAssistantMessage,
    AppendStreamingAssistant as AppendStreamingAssistant,
    AppendToolResult as AppendToolResult,
    AppendUserMessage as AppendUserMessage,
    ApprovalAlwaysGranted as ApprovalAlwaysGranted,
    ApprovalDecision as ApprovalDecision,
    ApprovalDenied as ApprovalDenied,
    ApprovalGranted as ApprovalGranted,
    ApproveAlways as ApproveAlways,
    ApproveOnce as ApproveOnce,
    AssistantMessageReceived as AssistantMessageReceived,
    AwaitApproval as AwaitApproval,
    CallModel as CallModel,
    CancelRequested as CancelRequested,
    CheckToolQueue as CheckToolQueue,
    ClearCurrentTool as ClearCurrentTool,
    ClearPendingTool as ClearPendingTool,
    ClearToolCallBatch as ClearToolCallBatch,
    DefaultRuntimeDataChangeApplier as DefaultRuntimeDataChangeApplier,
    DenyApproval as DenyApproval,
    EngineReady as EngineReady,
    ErrorOccurred as ErrorOccurred,
    Event as Event,
    FlushStreamingAssistant as FlushStreamingAssistant,
    InvariantViolationError as InvariantViolationError,
    MachineSnapshot as MachineSnapshot,
    ProtocolViolationError as ProtocolViolationError,
    ResetConversation as ResetConversation,
    ResetRequested as ResetRequested,
    RuntimeData as RuntimeData,
    RuntimeDataChange as RuntimeDataChange,
    RuntimeDataChangeApplier as RuntimeDataChangeApplier,
    RuntimeDataChangeResult as RuntimeDataChangeResult,
    RunTool as RunTool,
    ScheduledAction as ScheduledAction,
    SetCurrentTool as SetCurrentTool,
    SetPendingTool as SetPendingTool,
    SetToolCallBatch as SetToolCallBatch,
    SnapshotFrom as SnapshotFrom,
    ToolBatchFinished as ToolBatchFinished,
    ToolBatchReceived as ToolBatchReceived,
    ToolCallDenied as ToolCallDenied,
    ToolCallNeedsApproval as ToolCallNeedsApproval,
    ToolCallReadyToRun as ToolCallReadyToRun,
    ToolResultReceived as ToolResultReceived,
    Transition as Transition,
    TransitionResult as TransitionResult,
    UnexpectedEventError as UnexpectedEventError,
    UserMessageSubmitted as UserMessageSubmitted,
    ValidateRuntimeData as ValidateRuntimeData,
    ZeroState as ZeroState,
)

__all__ = [
    "ActionPlan",
    "AdvanceToolCallBatch",
    "AllEvents",
    "AllRuntimeDataChanges",
    "AllScheduledActions",
    "AppendAssistantMessage",
    "AppendStreamingAssistant",
    "AppendToolResult",
    "AppendUserMessage",
    "ApprovalAlwaysGranted",
    "ApprovalDecision",
    "ApprovalDenied",
    "ApprovalGranted",
    "ApproveAlways",
    "ApproveOnce",
    "AssistantMessageReceived",
    "AwaitApproval",
    "CallModel",
    "CancelRequested",
    "CheckToolQueue",
    "ClearCurrentTool",
    "ClearPendingTool",
    "ClearToolCallBatch",
    "DefaultRuntimeDataChangeApplier",
    "DenyApproval",
    "EngineReady",
    "ErrorOccurred",
    "Event",
    "FlushStreamingAssistant",
    "InvariantViolationError",
    "MachineSnapshot",
    "ProtocolViolationError",
    "ResetConversation",
    "ResetRequested",
    "RunTool",
    "RuntimeData",
    "RuntimeDataChange",
    "RuntimeDataChangeApplier",
    "RuntimeDataChangeResult",
    "ScheduledAction",
    "SetCurrentTool",
    "SetPendingTool",
    "SetToolCallBatch",
    "SnapshotFrom",
    "ToolBatchFinished",
    "ToolBatchReceived",
    "ToolCallDenied",
    "ToolCallNeedsApproval",
    "ToolCallReadyToRun",
    "ToolResultReceived",
    "Transition",
    "TransitionResult",
    "UnexpectedEventError",
    "UserMessageSubmitted",
    "ValidateRuntimeData",
    "ZeroState",
]
