"""Facade re-exports for ``runtime/execution``.

The execution compatibility surface, so callers can write
``runtime.new_default_policy()``. It is the only place the facade touches execution,
and it touches nothing else — R4 in
``tests/architecture/test_dependencies.py`` keeps it that way.
"""

from __future__ import annotations

from super_agent.runtime.execution import (
    ERR_APPROVAL_DISMISSED as ERR_APPROVAL_DISMISSED,
    PERMISSION_MODE_ACCEPT_EDITS as PERMISSION_MODE_ACCEPT_EDITS,
    PERMISSION_MODE_ASK as PERMISSION_MODE_ASK,
    PERMISSION_MODE_BYPASS as PERMISSION_MODE_BYPASS,
    PERMISSION_MODE_PLAN as PERMISSION_MODE_PLAN,
    ActionCompletion as ActionCompletion,
    ActionID as ActionID,
    ActionQueue as ActionQueue,
    ActionResultInput as ActionResultInput,
    ActionResultResolver as ActionResultResolver,
    ApprovalDismissed as ApprovalDismissed,
    ApprovalKey as ApprovalKey,
    ApprovalReceived as ApprovalReceived,
    ApprovalStore as ApprovalStore,
    ApprovalWaiter as ApprovalWaiter,
    CommandClass as CommandClass,
    DefaultActionResultResolver as DefaultActionResultResolver,
    DefaultPolicy as DefaultPolicy,
    DefaultRunController as DefaultRunController,
    DefaultScheduledActionExecutor as DefaultScheduledActionExecutor,
    DefaultScheduledActionRunner as DefaultScheduledActionRunner,
    MemoryApprovalStore as MemoryApprovalStore,
    ModelReplied as ModelReplied,
    PermissionMode as PermissionMode,
    PermissionRequest as PermissionRequest,
    PermissionRules as PermissionRules,
    Policy as Policy,
    QueuedAction as QueuedAction,
    RunController as RunController,
    RunID as RunID,
    ScheduledActionExecutor as ScheduledActionExecutor,
    ScheduledActionInput as ScheduledActionInput,
    ScheduledActionResult as ScheduledActionResult,
    ScheduledActionRunner as ScheduledActionRunner,
    ToolDecision as ToolDecision,
    ToolFinished as ToolFinished,
    ToolPolicyInput as ToolPolicyInput,
    ToolQueueChecked as ToolQueueChecked,
    hashCanonicalInput as hashCanonicalInput,
    new_approval_key as new_approval_key,
    new_default_policy as new_default_policy,
    new_policy as new_policy,
    valid_permission_mode as valid_permission_mode,
)

__all__ = [
    "ERR_APPROVAL_DISMISSED",
    "PERMISSION_MODE_ACCEPT_EDITS",
    "PERMISSION_MODE_ASK",
    "PERMISSION_MODE_BYPASS",
    "PERMISSION_MODE_PLAN",
    "ActionCompletion",
    "ActionID",
    "ActionQueue",
    "ActionResultInput",
    "ActionResultResolver",
    "ApprovalDismissed",
    "ApprovalKey",
    "ApprovalReceived",
    "ApprovalStore",
    "ApprovalWaiter",
    "CommandClass",
    "DefaultActionResultResolver",
    "DefaultPolicy",
    "DefaultRunController",
    "DefaultScheduledActionExecutor",
    "DefaultScheduledActionRunner",
    "MemoryApprovalStore",
    "ModelReplied",
    "PermissionMode",
    "PermissionRequest",
    "PermissionRules",
    "Policy",
    "QueuedAction",
    "RunController",
    "RunID",
    "ScheduledActionExecutor",
    "ScheduledActionInput",
    "ScheduledActionResult",
    "ScheduledActionRunner",
    "ToolDecision",
    "ToolFinished",
    "ToolPolicyInput",
    "ToolQueueChecked",
    "hashCanonicalInput",
    "new_approval_key",
    "new_default_policy",
    "new_policy",
    "valid_permission_mode",
]
