"""Facade re-exports for ``runtime/execution``.

The execution compatibility surface, so callers can write
``runtime.NewDefaultPolicy()``. It is the only place the facade touches execution,
and it touches nothing else — R4 in
``tests/architecture/test_dependencies.py`` keeps it that way.
"""

from __future__ import annotations

from super_agent.runtime.execution import (
    ActionCompletion as ActionCompletion,
    ActionID as ActionID,
    ActionQueue as ActionQueue,
    ActionResultInput as ActionResultInput,
    ActionResultResolver as ActionResultResolver,
    ApprovalDismissed as ApprovalDismissed,
    ApprovalKey as ApprovalKey,
    ApprovalReceived as ApprovalReceived,
    ApprovalStore as ApprovalStore,
    ApprovalWaiter as ApprovalWaiter,
    CommandClass as CommandClass,
    DefaultActionResultResolver as DefaultActionResultResolver,
    DefaultPolicy as DefaultPolicy,
    DefaultRunController as DefaultRunController,
    DefaultScheduledActionExecutor as DefaultScheduledActionExecutor,
    DefaultScheduledActionRunner as DefaultScheduledActionRunner,
    ErrApprovalDismissed as ErrApprovalDismissed,
    MemoryApprovalStore as MemoryApprovalStore,
    ModelReplied as ModelReplied,
    NewApprovalKey as NewApprovalKey,
    NewDefaultPolicy as NewDefaultPolicy,
    NewPolicy as NewPolicy,
    PermissionMode as PermissionMode,
    PermissionModeAcceptEdits as PermissionModeAcceptEdits,
    PermissionModeAsk as PermissionModeAsk,
    PermissionModeBypass as PermissionModeBypass,
    PermissionModePlan as PermissionModePlan,
    PermissionRequest as PermissionRequest,
    PermissionRules as PermissionRules,
    Policy as Policy,
    QueuedAction as QueuedAction,
    RunController as RunController,
    RunID as RunID,
    ScheduledActionExecutor as ScheduledActionExecutor,
    ScheduledActionInput as ScheduledActionInput,
    ScheduledActionResult as ScheduledActionResult,
    ScheduledActionRunner as ScheduledActionRunner,
    ToolDecision as ToolDecision,
    ToolFinished as ToolFinished,
    ToolPolicyInput as ToolPolicyInput,
    ToolQueueChecked as ToolQueueChecked,
    ValidPermissionMode as ValidPermissionMode,
    hashCanonicalInput as hashCanonicalInput,
)

__all__ = [
    "ActionCompletion",
    "ActionID",
    "ActionQueue",
    "ActionResultInput",
    "ActionResultResolver",
    "ApprovalDismissed",
    "ApprovalKey",
    "ApprovalReceived",
    "ApprovalStore",
    "ApprovalWaiter",
    "CommandClass",
    "DefaultActionResultResolver",
    "DefaultPolicy",
    "DefaultRunController",
    "DefaultScheduledActionExecutor",
    "DefaultScheduledActionRunner",
    "ErrApprovalDismissed",
    "MemoryApprovalStore",
    "ModelReplied",
    "NewApprovalKey",
    "NewDefaultPolicy",
    "NewPolicy",
    "PermissionMode",
    "PermissionModeAcceptEdits",
    "PermissionModeAsk",
    "PermissionModeBypass",
    "PermissionModePlan",
    "PermissionRequest",
    "PermissionRules",
    "Policy",
    "QueuedAction",
    "RunController",
    "RunID",
    "ScheduledActionExecutor",
    "ScheduledActionInput",
    "ScheduledActionResult",
    "ScheduledActionRunner",
    "ToolDecision",
    "ToolFinished",
    "ToolPolicyInput",
    "ToolQueueChecked",
    "ValidPermissionMode",
    "hashCanonicalInput",
]
