"""Durable session storage and the repository adapter over it.

The store package surface: everything callers write as ``store.X`` is re-exported
here.
"""

from __future__ import annotations

from super_agent.store.repository import (
    NewRepository as NewRepository,
    Repository as Repository,
    logPersistenceFailure as logPersistenceFailure,
    toSessionMetadata as toSessionMetadata,
    toSessionWorkspaceSpec as toSessionWorkspaceSpec,
    toStoreMetadata as toStoreMetadata,
    toStoreWorkspaceSpec as toStoreWorkspaceSpec,
)
from super_agent.store.store import (
    MAX_EVENT_BYTES as MAX_EVENT_BYTES,
    ZERO_TIME as ZERO_TIME,
    Checkpoint as Checkpoint,
    Compact as Compact,
    DefaultRoot as DefaultRoot,
    EventApprovalDecision as EventApprovalDecision,
    EventCancel as EventCancel,
    EventCheckpoint as EventCheckpoint,
    EventCompact as EventCompact,
    EventContextReplaced as EventContextReplaced,
    EventError as EventError,
    EventMessageAppended as EventMessageAppended,
    EventReset as EventReset,
    EventSessionStarted as EventSessionStarted,
    EventToolResult as EventToolResult,
    FileSnapshot as FileSnapshot,
    Fingerprint as Fingerprint,
    Metadata as Metadata,
    New as New,
    NewID as NewID,
    NewTurnID as NewTurnID,
    OpenDefault as OpenDefault,
    Record as Record,
    SessionID as SessionID,
    Store as Store,
    Summary as Summary,
    TurnID as TurnID,
    WorkspaceRootSpec as WorkspaceRootSpec,
    WorkspaceSpec as WorkspaceSpec,
    messagesFromRecords as messagesFromRecords,
    systemMessages as systemMessages,
    validateID as validateID,
    writeRecords as writeRecords,
)

__all__ = [
    "MAX_EVENT_BYTES",
    "ZERO_TIME",
    "Checkpoint",
    "Compact",
    "DefaultRoot",
    "EventApprovalDecision",
    "EventCancel",
    "EventCheckpoint",
    "EventCompact",
    "EventContextReplaced",
    "EventError",
    "EventMessageAppended",
    "EventReset",
    "EventSessionStarted",
    "EventToolResult",
    "FileSnapshot",
    "Fingerprint",
    "Metadata",
    "New",
    "NewID",
    "NewRepository",
    "NewTurnID",
    "OpenDefault",
    "Record",
    "Repository",
    "SessionID",
    "Store",
    "Summary",
    "TurnID",
    "WorkspaceRootSpec",
    "WorkspaceSpec",
    "logPersistenceFailure",
    "messagesFromRecords",
    "systemMessages",
    "toSessionMetadata",
    "toSessionWorkspaceSpec",
    "toStoreMetadata",
    "toStoreWorkspaceSpec",
    "validateID",
    "writeRecords",
]
