"""Durable session storage and the repository adapter over it.

The store package surface: everything callers write as ``store.X`` is re-exported
here.
"""

from __future__ import annotations

from super_agent.store.repository import (
    Repository as Repository,
    logPersistenceFailure as logPersistenceFailure,
    new_repository as new_repository,
    toSessionMetadata as toSessionMetadata,
    toSessionWorkspaceSpec as toSessionWorkspaceSpec,
    toStoreMetadata as toStoreMetadata,
    toStoreWorkspaceSpec as toStoreWorkspaceSpec,
)
from super_agent.store.store import (
    EVENT_APPROVAL_DECISION as EVENT_APPROVAL_DECISION,
    EVENT_CANCEL as EVENT_CANCEL,
    EVENT_CHECKPOINT as EVENT_CHECKPOINT,
    EVENT_COMPACT as EVENT_COMPACT,
    EVENT_CONTEXT_REPLACED as EVENT_CONTEXT_REPLACED,
    EVENT_ERROR as EVENT_ERROR,
    EVENT_MESSAGE_APPENDED as EVENT_MESSAGE_APPENDED,
    EVENT_RESET as EVENT_RESET,
    EVENT_SESSION_STARTED as EVENT_SESSION_STARTED,
    EVENT_TOOL_RESULT as EVENT_TOOL_RESULT,
    MAX_EVENT_BYTES as MAX_EVENT_BYTES,
    ZERO_TIME as ZERO_TIME,
    Checkpoint as Checkpoint,
    Compact as Compact,
    FileSnapshot as FileSnapshot,
    Metadata as Metadata,
    Record as Record,
    SessionID as SessionID,
    Store as Store,
    Summary as Summary,
    TurnID as TurnID,
    WorkspaceRootSpec as WorkspaceRootSpec,
    WorkspaceSpec as WorkspaceSpec,
    default_root as default_root,
    fingerprint as fingerprint,
    messagesFromRecords as messagesFromRecords,
    new as new,
    new_id as new_id,
    new_turn_id as new_turn_id,
    open_default as open_default,
    systemMessages as systemMessages,
    validateID as validateID,
    writeRecords as writeRecords,
)

__all__ = [
    "EVENT_APPROVAL_DECISION",
    "EVENT_CANCEL",
    "EVENT_CHECKPOINT",
    "EVENT_COMPACT",
    "EVENT_CONTEXT_REPLACED",
    "EVENT_ERROR",
    "EVENT_MESSAGE_APPENDED",
    "EVENT_RESET",
    "EVENT_SESSION_STARTED",
    "EVENT_TOOL_RESULT",
    "MAX_EVENT_BYTES",
    "ZERO_TIME",
    "Checkpoint",
    "Compact",
    "FileSnapshot",
    "Metadata",
    "Record",
    "Repository",
    "SessionID",
    "Store",
    "Summary",
    "TurnID",
    "WorkspaceRootSpec",
    "WorkspaceSpec",
    "default_root",
    "fingerprint",
    "logPersistenceFailure",
    "messagesFromRecords",
    "new",
    "new_id",
    "new_repository",
    "new_turn_id",
    "open_default",
    "systemMessages",
    "toSessionMetadata",
    "toSessionWorkspaceSpec",
    "toStoreMetadata",
    "toStoreWorkspaceSpec",
    "validateID",
    "writeRecords",
]
